"""empty message

Revision ID: 9977f9f9fba9
Revises: 42cf9a05e9b9
Create Date: 2023-10-10 09:16:25.775387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9977f9f9fba9'
down_revision = '42cf9a05e9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor_formacao',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('formacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formacao_id'], ['formacao.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'formacao_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor_formacao')
    # ### end Alembic commands ###
