"""empty message

Revision ID: e1e4cce3f7f5
Revises: 5ced4a8dcd8a
Create Date: 2023-10-06 13:54:45.820088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e4cce3f7f5'
down_revision = '5ced4a8dcd8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formacao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'formacao', ['formacao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('formacao_id')

    # ### end Alembic commands ###
